# Generated by Django 5.0.7 on 2024-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Brand_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
