# Generated by Django 5.0.7 on 2024-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textileapp', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
