# Generated by Django 5.0.7 on 2024-07-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Textileapp', '0003_alter_productdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
