# Generated by Django 5.0.7 on 2024-08-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_registerdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='First_Name',
            new_name='Password1',
        ),
        migrations.RenameField(
            model_name='registerdb',
            old_name='Gender',
            new_name='Password2',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='Password',
        ),
    ]
