# Generated by Django 5.0.7 on 2024-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Wishlist Images')),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
